[package]
authors = ["Gurinder Singh <gurinder.singh@1e.com>"]
license = "MIT"
name = "futures-ext"
repository = "https://github.com/gurry/futures-ext"
version = "0.1.0"

[dependencies]
futures = "0.1.17"
futures-cpupool = "0.1.7"
lazy_static = "0.2.11"
tokio-timer = "0.1.2"
