[package]
authors = ["Gurinder Singh <gurinder.singh@1e.com>"]
name = "futures-ext"
version = "0.1.0"
repository = "https://github.com/gurry/futures-ext"
license = "MIT"

[dependencies]
futures = "0.1.17"
futures-cpupool = "0.1.7"
lazy_static = "0.2.11"
